spring:
  application:
    name: ferrientregas
  datasource:
    url: jdbc:mysql://localhost:3306/ferrientregas
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
# Server configurations
server:
  error:
    include-stacktrace: never
# JWT
api:
  security:
    secret: ZmVycmllbnRyZWdhczIwMjU=
    expiration: 560000

cors:
  allowed:
    origins: http://localhost:4200

