spring:
  application:
    name: ferrientregas
  datasource:
    url: jdbc:mysql://localhost:3306/ferrientregas
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariDataSource
      maximum-pool-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: systemgym0001@gmail.com
    password: vswetusjdoxtufvs
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
  flyway:
    baseline-on-migrate: true
# Server configurations
server:
  error:
    include-stacktrace: never
# JWT
api:
  security:
    secret: 9ddb40a3718e268a985f6ebedb4035183bde2af57fe1084b3c2208ff57bd4af3
    expiration: 560000

#CORS
cors:
  allowed:
    origins: http://localhost:4200

