spring:
  application:
    name: ferrientregas
  datasource:
    url: jdbc:mysql://localhost:3306/ferrientregas
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariDataSource
      maximum-pool-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
# Server configurations
server:
  error:
    include-stacktrace: never
# JWT
api:
  security:
    secret: aedb5581186c3017a42eb982bf1f6422005f2de1a3729d700f6ae44eb99deba3
    expiration: 560000

cors:
  allowed:
    origins: http://localhost:4200

